config/routes.rb
Rails.application.routes.draw do

  
  
  resources :payment_states
  resources :feedbacks
  resources :subscription_remarks
  resources :subs_payments
  # resources :payment_states
  # resources :subs_payments
  # resources :subscription_remarks
  resources :subscription_new_mains
  # resources :feedbacks
  # root pages 
 
  resources :callback_statuses
  resources :payment_reqs
  resources :pre_payment_reqs
  resources :medication_details
  resources :service_fee_masters
  resources :billing_info_bill_items
  resources :patient_billing_infos
  resources :measure_units
  resources :drug_prices
  resources :drug_masters
  resources :decline_comments
  resources :pre_confirmed_appointments
  resources :referals
  resources :patient_med_records
  resources :pds_patient_prev_med_histories
  resources :confirmed_personal_doctor_services
  resources :engaged_user_services
  resources :user_services
  resources :roles
  resources :permission_roles
  resources :permissions
  resources :events
  resources :profesional_groups 
  resources :specialty_masters
  resources :confirmed_conditions
  resources :condition_masters
  resources :lab_detail_images
  resources :registrations
  resources :lab_details
  resources :lab_services
  resources :confirmed_appointments
  resources :requester_allergies
  resources :request_urgencies
  resources :request_categories
  devise_for :users
  resources :pre_appointments
  resources :appointment_types
  resources :allergies_masters
  resources :affected_system_masters
  resources :person_info_extras
  resources :person_contact_infos
  resources :provider_engaged_users
  resources :person_infos
  resources :person_type_masters
  resources :provider_masters
  resources :provider_services
  resources :service_prov_extra_infos
  resources :service_masters
  resources :service_prov_types
  resources :suburb_masters
  resources :city_town_masters
  resources :region_masters 
  resources :country_masters

   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # root pages 
  
  root 'home#welcome'

  get 'home/about' => 'home#welcome'
  
   get 'home/index', as: 'index' 
  #  get 'home/about', as: 'about'
  #  get 'home/services', as: 'services'
  #  get 'home/pricing', as: 'pricing'
  #  get 'home/blog', as: 'blog'
  #  get 'home/contact', as:  'contact'
   get 'home/elderlycare', as: 'elderlycare'
   get 'home/chronic_disease', as: 'chronic_disease'
   get 'home/annual_screening', as: 'annual_screening'
   get 'client_home/elderly', as: 'elderly'
   get 'client_home/elderlycare1', as: 'elderlycare1'
   get 'client_home/elderly_two', as: 'elderly_two'
   get 'client_home/elderly_three', as: 'elderly_three'
   get 'client_home/chronic_one', as: 'chronic_one'
   get 'client_home/chronic_two', as: 'chronic_two'
   get 'client_home/annual_screen_one', as: 'annual_screen_one'
   get 'client_home/annual_screen_two', as: 'annual_screen_two'
   get 'client_home/doctor_subscription', as: 'doctor_subscription'
   get 'client_home/doc_sub_detail', as: 'doc_sub_detail'
   get 'client_home/doc_remark_info', as: 'doc_remark_info'
   get 'client_home/subscriber_info', as: 'subscriber_info'
   get 'client_home/user_subs_detail', as: 'user_subs_detail'
   get 'client_home/user_pay', as: 'user_pay'
   get 'client_home/edit_info' => 'edit_info'



   post 'elderly_user_info' =>        'client_home#elderly_user_info'
   post 'elderly_user_info_two' =>        'client_home#elderly_user_info_two'
   post 'elderly_user_info_three' =>        'client_home#elderly_user_info_three'

   post 'chronic_user_info_one' =>        'client_home#chronic_user_info_one'
   post 'chronic_user_info_two' =>        'client_home#chronic_user_info_two'

   post 'annual_user_info_one' =>        'client_home#annual_user_info_one'
   post 'annual_user_info_two' =>        'client_home#annual_user_info_two' 
   

   post 'update_subscription' => 'subscription_new_mains#update_subscription'
   post 'remark_sub' => 'subscription_new_mains#remark_sub'
   post 'payme_user' => 'subscription_new_mains#payme_user'
   post 'ghinger_momo_callback' => 'home#ghinger_momo_callback'
   post 'ghinger_visa_callback' => 'home#ghinger_visa_callback'
  

  
  # Admin root path
   get '/admin/index' => 'admin#index', :as => 'admin_root'
   
  # doctor root path
  get '/doctor_home/index' => 'doctor_home#index', :as => 'doctor_root'
  
  # nurse root path
  get '/nurse_home/index' => 'nurse_home#index', :as => 'nurse_root'
  
  
  
   
  
  # resources :provider_masters do 
    # resources :service_prov_extra_infos
  # end 
  
  
  namespace :api do
    namespace :v1 do
       resources :person_infos
    end
     
  end
  
 
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  
  get 'profile' => 'users#profile'
  get 'edit_profile' => 'person_infos#edit_profile'
  patch 'update_profile' => 'person_infos#update_profile'
  
  # credentials
  get 'user_credential' => 'users#user_credential'
  patch 'update_credential' => 'users#update_credential'
  
  
  
  
  # Enable and Disable country
  get       'enable_country'    =>  'country_masters#enable_country'
  get       'disable_country'   =>  'country_masters#disable_country'
  
  # Enable and disable region
  get       'enable_region'    =>  'region_masters#enable_region'
  get       'disable_region'   =>  'region_masters#disable_region'
  
  # Enable and disable city
  get       'enable_city'    =>  'city_town_masters#enable_city'
  get       'disable_city'   =>  'city_town_masters#disable_city'
  
  # Enable and disable suburb
  get       'enable_suburb'    =>  'suburb_masters#enable_suburb'
  get       'disable_suburb'   =>  'suburb_masters#disable_suburb'
  
  # Enable and disable provider type
  get       'enable_prov_type'    =>  'service_prov_types#enable_prov_type'
  get       'disable_prov_type'   =>  'service_prov_types#disable_prov_type'
  
  # Enable and disable service
  get       'enable_service'    =>  'service_masters#enable_service'
  get       'disable_service'   =>  'service_masters#disable_service'
  
  # Enable and disable service provider
  get       'enable_service_provider'    =>  'provider_masters#enable_service_provider'
  get       'disable_service_provider'   =>  'provider_masters#disable_service_provider'
  
  # Enable and disable provider service
  get       'enable_provider_service'    =>  'provider_services#enable_provider_service'
  get       'disable_provider_service'   =>  'provider_services#disable_provider_service'
  
  
  # Enable and disable user type
  get       'enable_user_type'    =>  'person_type_masters#enable_user_type'
  get       'disable_user_type'   =>  'person_type_masters#disable_user_type'
  
  
  # Enable and disable player
  get       'enable_player'    =>  'person_infos#enable_player'
  get       'disable_player'   =>  'person_infos#disable_player' 
  
    
  # Enable and disable human part
  get       'enable_part'    =>  'affected_system_masters#enable_part'
  get       'disable_part'   =>  'affected_system_masters#disable_part'  
  
     
  # Enable and disable allergy
  get       'enable_allergy'    =>  'allergies_masters#enable_allergy'
  get       'disable_allergy'   =>  'allergies_masters#disable_allergy' 
  
  # Enable and disable appointment type
  get       'enable_appointment_type'    =>  'appointment_types#enable_appointment_type'
  get       'disable_appointment_type'   =>   'appointment_types#disable_appointment_type'
  
  
  # Enable and disable pre_appointment
  get       'enable_pre_appointment'    =>  'pre_appointments#enable_pre_appointment'
  get       'disable_pre_appointment'   =>   'pre_appointments#disable_pre_appointment'
  
  # Enable and disable confirmed appointment
  get       'enable_appointment'    =>  'confirmed_appointments#enable_appointment'
  get       'disable_appointment'   =>   'confirmed_appointments#disable_appointment'
  
  # Enable and disable pre confirmed appointment
  get       'enable_pre_confirmed_appointment'    =>  'pre_confirmed_appointments#enable_pre_confirmed_appointment'
  get       'disable_pre_confirmed_appointment'   =>   'pre_confirmed_appointments#disable_pre_confirmed_appointment'
 
 # Enable and disable lab_service
  get       'enable_lab_service'    =>  'lab_services#enable_lab_service'
  get       'disable_lab_service'   =>  'lab_services#disable_lab_service'
  
  # Enable and disable pending registration
  get       'enable_pending_reg'    =>  'registrations#enable_pending_reg'
  get       'disable_pending_reg'   =>  'registrations#disable_pending_reg'

  # Enable and disable pending drug master
  get       'enable_drug'    =>  'drug_masters#enable_drug'
  get       'disable_drug'   =>  'drug_masters#disable_drug'

  # Enable and disable pending drug measuring unit
  get       'enable_unit'    =>  'measure_units#enable_unit'
  get       'disable_unit'   =>  'measure_units#disable_unit'

  # Enable and disable pending drug measuring unit
  get       'enable_price'    =>  'service_fee_masters#enable_price'
  get       'disable_price'   =>  'service_fee_masters#disable_price'





  # Approve registration
  get       'approve_registration'   =>  'registrations#approve_registration'
  get       'new_confirm_person_info'   =>  'person_info_extras#new_confirm_person_info' 
  post       'create_reg_confirm'   =>  'person_infos#create_reg_confirm'  
  post      'confirm_person_registration'   =>  'person_info_extras#confirm_person_registration'
  # post      'confirm_person_registration_prof_info'   =>  'person_infos#confirm_person_registration_prof'  
  

app/controllers/service_fee_masters_controller.rb
class ServiceFeeMastersController < ApplicationController
  before_action :set_service_fee_master, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  # load_and_authorize_resource
  # before_filter :load_permissions

  # GET /service_fee_masters
  # GET /service_fee_masters.json
  def index
    @ref_id = params[:ref_id]

    if @ref_id.present?
      @service_fee_masters = ServiceFeeMaster.where(appt_type_id: @ref_id).paginate(:page => params[:page], :per_page => 8).order('created_at desc')
    else
    @service_fee_masters = ServiceFeeMaster.all.paginate(:page => params[:page], :per_page => 8).order('created_at desc')
    end

    respond_to do |format|
      format.html
      format.csv { send_data @service_fee_masters.to_csv }
      format.xls { send_data @service_fee_masters.to_csv(options={col_sep: "\t"}) }
    end
  end

  def all_price_excel
    @service_fee_masters = ServiceFeeMaster.all.order('created_at desc')
    respond_to do |format|
      # format.json {render json: @search_json[1..10]}
      # p "JSON ARRAY: #{@search_json}"
      format.html
      # format.js
      format.csv { send_data @service_fee_masters.to_csv }
      format.xls { send_data @service_fee_masters.to_csv(options={col_sep: "\t"}) }
    end
  end

  # GET /service_fee_masters/1
  # GET /service_fee_masters/1.json
  def show
  end

  def enable_price
    price_id = params[:chosen]
    price = ServiceFeeMaster.find(price_id)
    if price.update(:active_status => 1)
      redirect_to service_fee_masters_path, notice: 'Drug was successfully enabled.'
    end
  end

  def disable_price
    price_id=params[:chosen]
    price = ServiceFeeMaster.find(price_id)
    if price.update(:active_status => 0)
      redirect_to service_fee_masters_path, notice: 'Drug was successfully disabled.'
    end
  end

  # GET /service_fee_masters/new
  def new
    @service_fee_master = ServiceFeeMaster.new
    @lab_services = LabService.order(:title).where("title ilike ?", "%#{params[:service_id]}")

    @lab_list = @lab_services.map { |a|[a.title+" ",a.id]  }
  end

  # GET /service_fee_masters/1/edit
  def edit
    @lab_services = LabService.order(:title).where("title ilike ?", "%#{params[:service_id]}")

    @lab_list = @lab_services.map { |a|[a.title+" ",a.id]  }
  end

  # POST /service_fee_masters
  # POST /service_fee_masters.json
  def create
    @service_fee_master = ServiceFeeMaster.new(service_fee_master_params)

    @lab_services = LabService.order(:title).where("title ilike ?", "%#{params[:service_id]}")

    @lab_list = @lab_services.map { |a|[a.title+" ",a.id]  }

    respond_to do |format|
      if @service_fee_master.save
        format.js {flash[:notice] = "Service Price set successfully"}
        render js: "window.location='#{service_fee_masters_path}'"
        # format.html { redirect_to @service_fee_master, notice: 'Service fee master was successfully created.' }
        format.json { render :show, status: :created, location: @service_fee_master }
      else
        format.js {render :new }
        # format.html { render :new }
        format.json { render json: @service_fee_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_fee_masters/1
  # PATCH/PUT /service_fee_masters/1.json
  def update
    respond_to do |format|
      @lab_services = LabService.order(:title).where("title ilike ?", "%#{params[:service_id]}")

      @lab_list = @lab_services.map { |a|[a.title+" ",a.id]  }
      if @service_fee_master.update(service_fee_master_params)
        format.js {flash[:notice] = "Service Price updated successfully"}
        render js: "window.location='#{service_fee_masters_path}'"
        # format.html { redirect_to @service_fee_master, notice: 'Service fee master was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_fee_master }
      else
        format.js { render :edit }
        # format.html { render :edit }
        format.json { render json: @service_fee_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_fee_masters/1
  # DELETE /service_fee_masters/1.json
  def destroy
    @service_fee_master.destroy
    respond_to do |format|
      format.html { redirect_to service_fee_masters_url, notice: 'Service fee master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_fee_master
      @service_fee_master = ServiceFeeMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_fee_master_params
      params.require(:service_fee_master).permit(:appt_type_id, :service_id, :req_urgency, :fee, :fee, :comment, :user_id, :active_status, :del_status)
    end
end

app/helpers/service_fee_masters_helper.rb
module ServiceFeeMastersHelper
end

app/views/service_fee_masters/_edit.html.erb
<br>
<%= simple_form_for @service_fee_master, :remote => true  do |f| %>
    <div id="id01" class="w3-modal w3-card-4 w3-round-large" style="display: block;">
      <div class="w3-modal-content w3-animate-top w3-card-4 w3-light-gray" style="width: 30%; max-height: 80%; overflow-y: auto;">
        <div style="max-width: 70%; text-align: center; margin-left: 15%; margin-top: 15px">
          <header class="w3-container">
            <h4>Service Price</h4>
          </header>
          <% if flash[:notice] %>
              <p class="flash_notice " id = 'notes' style = ""><%= notice %></p>
          <% end %>
        </div>
        <div class="w3-container" >
          <div class="form-inputs">
            <%= f.input :appt_type_id, collection: AppointmentType.where("appointment_types.ref_id !=? and appointment_types.ref_id !=? and appointment_types.ref_id !=?", "MA", "PD", "MD"), label_method: :title, value_method: :ref_id, input_html:{id: "appt_type"} %>
              <span class="hidden" id="service">
                <%= f.input :service_id, collection:  @lab_list,  label_method: :first, value_method: :last, input_html:{class:"combobox form-control", data: { placeholder: "Select lab service" } } %>
              </span>
            <%= f.input :req_urgency, collection: RequestUrgency.all, label_method: :urgency, value_method: :ref_id %>
            <%= f.input :fee %>
            <%= f.label :comment, "Comment"%>
            <%= f.text_area :comment, :rows=> 5, style: "width: 100%;"%>
            <%#= f.input :user_id, as: :hidden, input_html: {value: current_user.id } %>
            <%##= f.input :active_status, as: :hidden, input_html: {value: 1} %>
            <%#= f.input :del_status, as: :hidden, input_html: {value: 0}  %>
          </div>
        </div>
        <br>
        <footer class="w3-container">
          <%= f.button :submit, class: "w3-button w3-teal w3-hover-teal w3-right w3-card-4 w3-small w3-round-xlarge", value: "Submit" %>

          <span class="w3-button w3-black w3-hover-black w3-left w3-card-4 w3-small w3-round-xlarge" onclick="document.getElementById('id01').style.display='none'">Back</span>
          <br />
        </footer>
<% end %>
<br />
</div>
<br />
</div>

<script>
    $(document).ready(function () {
        var appt_type;
        appt_type = document.getElementById("appt_type").value;
        if(appt_type == "LA"){
            $("#service").removeClass("hidden");
        }
        else
        {
            $("#service").addClass("hidden");
            $("#service").value = " ";
//          document.getElementById("service").value = " ";
        }

        $("#appt_type").change(function () {
//          alert("changed");
            appt_type = document.getElementById("appt_type").value;
//          alert(appt_type);
            if(appt_type == "LA"){
                $("#service").removeClass("hidden");
            }
            else
            {
                $("#service").addClass("hidden");
                $("#service").value = " ";
//              document.getElementById("service").value = " ";
            }
        });
    })
</script>
<style>
    .input-group{
        width: 100%;
    }
    .typeahead{
        width: 100%;
    }

</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('form').attr('autocomplete', 'off');

        $('.combobox').combobox();

        $('span.input-group-addon').addClass("hidden");

    });
</script>

app/views/service_fee_masters/_form.html.erb
<br>
<%= simple_form_for @service_fee_master, :remote => true  do |f| %>
    <div id="id01" class="w3-modal w3-card-4 w3-round-large" style="display: block;">
      <div class="w3-modal-content w3-animate-top w3-card-4 w3-light-gray" style="width: 30%; max-height: 80%; overflow-y: auto;">
        <div style="max-width: 70%; text-align: center; margin-left: 15%; margin-top: 15px">
          <header class="w3-container">
            <h4>Service Price</h4>
          </header>
          <% if flash[:notice] %>
              <p class="flash_notice " id = 'notes' style = ""><%= notice %></p>
          <% end %>
        </div>
        <div class="w3-container" >
          <div class="form-inputs">
              <%= f.input :appt_type_id, collection: AppointmentType.where("appointment_types.ref_id !=? and appointment_types.ref_id !=? and appointment_types.ref_id !=?", "MA", "PD", "MD"), label_method: :title, value_method: :ref_id, input_html:{id: "appt_type"} %>
              <span class="hidden" id="service">
                <%= f.input :service_id, collection:  @lab_list,  label_method: :first, value_method: :last, input_html:{class:"combobox form-control", data: { placeholder: "Select lab service" } } %>
              </span>
              <%= f.input :req_urgency, collection: RequestUrgency.all, label_method: :urgency, value_method: :ref_id %>
              <%= f.input :fee %>
              <%= f.label :comment, "Comment"%>
              <%= f.text_area :comment, :rows=> 5, style: "width: 100%;"%>
              <%= f.input :user_id, as: :hidden, input_html: {value: current_user.id } %>
              <%= f.input :active_status, as: :hidden, input_html: {value: 1} %>
              <%= f.input :del_status, as: :hidden, input_html: {value: 0}  %>
          </div>
        </div>
        <br>
        <footer class="w3-container">
          <%= f.button :submit, class: "w3-button w3-teal w3-hover-teal w3-right w3-card-4 w3-small w3-round-xlarge", value: "Submit" %>

          <span class="w3-button w3-black w3-hover-black w3-left w3-card-4 w3-small w3-round-xlarge" onclick="document.getElementById('id01').style.display='none'">Back</span>
          <br />
        </footer>
<% end %>
<br />
</div>
<br />
</div>

<script>
  $(document).ready(function () {
      var appt_type;
      appt_type = document.getElementById("appt_type").value;
      if(appt_type == "LA"){
          $("#service").removeClass("hidden");
      }
      else
      {
          $("#service").addClass("hidden");
          $("#service").value = " ";
//          document.getElementById("service").value = " ";
      }

      $("#appt_type").change(function () {
//          alert("changed");
          appt_type = document.getElementById("appt_type").value;
//          alert(appt_type);
          if(appt_type == "LA"){
              $("#service").removeClass("hidden");
          }
          else
          {
              $("#service").addClass("hidden");
              $("#service").value = " ";
//              document.getElementById("service").value = " ";
          }
      });
  })
</script>
<style>
    .input-group{
        width: 100%;
    }
    .typeahead{
        width: 100%;
    }

</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('form').attr('autocomplete', 'off');

        $('.combobox').combobox();

        $('span.input-group-addon').addClass("hidden");

    });
</script>

app/views/service_fee_masters/edit.html.erb
<h1>Editing Service Fee Master</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_fee_master %> |
<%= link_to 'Back', service_fee_masters_path %>

app/views/service_fee_masters/edit.js.erb
$("#modalDiv").html("<%= escape_javascript(render(:partial =>"edit")) %>");

app/views/service_fee_masters/index.html.erb
<div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2">
  <h4>Service Price List</h4>
  <div id="new"></div>
  <div class="pull-right" style = 'margin-top: -3%; '>
    <label class="">Display <u>No</u>: </label>
    <!-- <%#= select_tag :count, options_for_select([5,10,15,20,25,30], params[:count].to_i), :onchange => "if(this.value){ window.location='?count='+this.value ;}" %> -->
    <%= select_tag :per_page, options_for_select([15, 30, 40,50, 70,100], params[:per_page].to_i), :data => { :remote => true,
                            :url => url_for( :controller => "service_fee_masters", :action => "index" )
                            }, :onchange => "if(this.value){window.location='?per_page='+this.value;}", class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4" %>
  </div>

  <div class="pull-left" style = 'margin-top: -3%;'>
    <label class="">Filter by: </label><br>
    <%= select_tag :ref_id, options_from_collection_for_select(AppointmentType.where("appointment_types.ref_id !=? and appointment_types.ref_id !=? and appointment_types.ref_id !=?", "MA", "PD", "MD"), "ref_id", "title",  'ref_id'), :data => {
        :url => url_for(:controller => "service_fee_masters", :action => "index")},
         :onchange => "window.location.href = '?ref_id='+this.value;",
        class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4",
       :prompt => "Appointment Type", style: "max-width: 90%; width: 8%; min-width: 70%" %>
    <%#= form_tag drug_masters_path, :method => 'get', class: "form-inline", html: { autocomplete: "off" }, :id => "drug_search" do %>
        <%#= text_field_tag :drug_name, params[:drug_name], class: "form-control w3-bordered ", :placeholder=> "Filter by Drug  Name", autocomplete: "off"  %>
        <%#= submit_tag "Search", :name => nil,  class: "w3-btn w3-round w3-blue w3-tiny", id: "submitBtn" %>
    <%# end %>
  </div>

  <br /><br>
  <p style = 'text-align: center; font-family: tahoma; font-size: 15px;'>
    <b>Download:</b>  <%= link_to "CSV", service_fee_masters_path(format: "csv"), :class => "w3-hover-white"%>
    | <%= link_to "Excel", service_fee_masters_path(format: "xls"), :class => "w3-hover-white" %>
    | <%= link_to "CSV-all", all_price_excel_path(format: "csv"), :class => "w3-hover-white", method: :get%>
    | <%= link_to "Excel-all", all_price_excel_path(format: "xls"),:class => "w3-hover-white", method: :get%>
  </p>
  <% if @ref_id.present? %>
      <%= link_to  service_fee_masters_path, class: "w3-hover-none" do %>
        <span class="fa fa-refresh fa-2x"></span>
      <% end %>
  <% end %>
  <div class="table-responsive">
    <table class="table table-condensed table-bordered table-striped w3-card">
      <thead>
      <tr class="w3-teal">
        <th>S/N</th>
        <th>Appt Type</th>
        <th>Service</th>
        <th>Urgency</th>
        <th>Price (GHS)</th>
        <th>Status</th>
        <th colspan="2">Options</th>
      </tr>
      </thead>
      <tbody>
      <% @service_fee_masters.each_with_index  do |service_fee_master, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= service_fee_master.appointment_type.title %></td>
            <td>
              <% if  service_fee_master.service_id.present? %>
                <%= service_fee_master.lab_service.title %>
              <% else %>
                <span style="color: red;">Not Applicable</span>
              <% end %>
            </td>
            <td>
              <% if service_fee_master.req_urgency == "S" %>
                Standard
              <% elsif service_fee_master.req_urgency == "E" %>
                Express
              <% end %>
            </td>
            <td><%= number_to_currency(service_fee_master.fee, unit: " ")  %></td>
            <% if service_fee_master.active_status%>
                <td >Active</td>
            <% else %>
                <td style="color: red">Inactive</td>
            <% end %>

            <td style="width: 15px"><%= link_to 'Edit', edit_service_fee_master_path(service_fee_master), remote: true,  class: "w3-button w3-gray w3-card w3-hover-gray w3-small w3-round w3-round-xxlarge" %></td>

            <td style="width: 15px">
              <% if service_fee_master.active_status == false %>
                  <%= link_to 'Enable', enable_price_path(:chosen => service_fee_master.id), data: { confirm: 'You are about to enable the selected price, do you want to continue?' },  class: "w3-button w3-blue w3-hover-blue w3-small w3-round-xxlarge w3-card" %>

              <% elsif service_fee_master.active_status == true %>
                  <%= link_to 'Disable', disable_price_path(:chosen => service_fee_master.id), data: { confirm: 'You are about to disable the selected price, do you want to continue?' },  class: "w3-button w3-red w3-hover-red w3-small w3-round w3-round-xxlarge w3-card" %>

              <% end %>
            </td>

          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div>
    <%= link_to '+', new_service_fee_master_path, remote: true, class: "w3-button w3-circle w3-teal w3-hover-teal w3-left w3-card-4" %>
    <%= will_paginate @service_fee_masters,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4" %>
    <br /><br>
  </div>
</div>
<hr>
<div class="clearfix w3-clear"></div>
<br><br>

app/views/service_fee_masters/new.html.erb
<h1>New Service Fee Master</h1>

<%= render 'form' %>

<%= link_to 'Back', service_fee_masters_path %>

app/views/service_fee_masters/new.js.erb
$("#modalDiv").html("<%= escape_javascript(render(:partial =>"form")) %>");

app/views/service_fee_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appt type:</strong>
  <%= @service_fee_master.appt_type_id %>
</p>

<p>
  <strong>Service:</strong>
  <%= @service_fee_master.service_id %>
</p>

<p>
  <strong>Req urgency:</strong>
  <%= @service_fee_master.req_urgency %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @service_fee_master.fee %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @service_fee_master.fee %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @service_fee_master.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @service_fee_master.user_id %>
</p>

<p>
  <strong>Active status:</strong>
  <%= @service_fee_master.active_status %>
</p>

<p>
  <strong>Del status:</strong>
  <%= @service_fee_master.del_status %>
</p>

<%= link_to 'Edit', edit_service_fee_master_path(@service_fee_master) %> |
<%= link_to 'Back', service_fee_masters_path %>