config/routes.rb
Rails.application.routes.draw do

  
  
  resources :payment_states
  resources :feedbacks
  resources :subscription_remarks
  resources :subs_payments
  # resources :payment_states
  # resources :subs_payments
  # resources :subscription_remarks
  resources :subscription_new_mains
  # resources :feedbacks
  # root pages 
 
  resources :callback_statuses
  resources :payment_reqs
  resources :pre_payment_reqs
  resources :medication_details
  resources :service_fee_masters
  resources :billing_info_bill_items
  resources :patient_billing_infos
  resources :measure_units
  resources :drug_prices
  resources :drug_masters
  resources :decline_comments
  resources :pre_confirmed_appointments
  resources :referals
  resources :patient_med_records
  resources :pds_patient_prev_med_histories
  resources :confirmed_personal_doctor_services
  resources :engaged_user_services
  resources :user_services
  resources :roles
  resources :permission_roles
  resources :permissions
  resources :events
  resources :profesional_groups 
  resources :specialty_masters
  resources :confirmed_conditions
  resources :condition_masters
  resources :lab_detail_images
  resources :registrations
  resources :lab_details
  resources :lab_services
  resources :confirmed_appointments
  resources :requester_allergies
  resources :request_urgencies
  resources :request_categories
  devise_for :users
  resources :pre_appointments
  resources :appointment_types
  resources :allergies_masters
  resources :affected_system_masters
  resources :person_info_extras
  resources :person_contact_infos
  resources :provider_engaged_users
  resources :person_infos
  resources :person_type_masters
  resources :provider_masters
  resources :provider_services
  resources :service_prov_extra_infos
  resources :service_masters
  resources :service_prov_types
  resources :suburb_masters
  resources :city_town_masters
  resources :region_masters 
  resources :country_masters

   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # root pages 
  
  root 'home#welcome'

  get 'home/about' => 'home#welcome'
  
   get 'home/index', as: 'index' 
  #  get 'home/about', as: 'about'
  #  get 'home/services', as: 'services'
  #  get 'home/pricing', as: 'pricing'
  #  get 'home/blog', as: 'blog'
  #  get 'home/contact', as:  'contact'
   get 'home/elderlycare', as: 'elderlycare'
   get 'home/chronic_disease', as: 'chronic_disease'
   get 'home/annual_screening', as: 'annual_screening'
   get 'client_home/elderly', as: 'elderly'
   get 'client_home/elderlycare1', as: 'elderlycare1'
   get 'client_home/elderly_two', as: 'elderly_two'
   get 'client_home/elderly_three', as: 'elderly_three'
   get 'client_home/chronic_one', as: 'chronic_one'
   get 'client_home/chronic_two', as: 'chronic_two'
   get 'client_home/annual_screen_one', as: 'annual_screen_one'
   get 'client_home/annual_screen_two', as: 'annual_screen_two'
   get 'client_home/doctor_subscription', as: 'doctor_subscription'
   get 'client_home/doc_sub_detail', as: 'doc_sub_detail'
   get 'client_home/doc_remark_info', as: 'doc_remark_info'
   get 'client_home/subscriber_info', as: 'subscriber_info'
   get 'client_home/user_subs_detail', as: 'user_subs_detail'
   get 'client_home/user_pay', as: 'user_pay'
   get 'client_home/edit_info' => 'edit_info'



   post 'elderly_user_info' =>        'client_home#elderly_user_info'
   post 'elderly_user_info_two' =>        'client_home#elderly_user_info_two'
   post 'elderly_user_info_three' =>        'client_home#elderly_user_info_three'

   post 'chronic_user_info_one' =>        'client_home#chronic_user_info_one'
   post 'chronic_user_info_two' =>        'client_home#chronic_user_info_two'

   post 'annual_user_info_one' =>        'client_home#annual_user_info_one'
   post 'annual_user_info_two' =>        'client_home#annual_user_info_two' 
   

   post 'update_subscription' => 'subscription_new_mains#update_subscription'
   post 'remark_sub' => 'subscription_new_mains#remark_sub'
   post 'payme_user' => 'subscription_new_mains#payme_user'
   post 'ghinger_momo_callback' => 'home#ghinger_momo_callback'
   post 'ghinger_visa_callback' => 'home#ghinger_visa_callback'
  

  
  # Admin root path
   get '/admin/index' => 'admin#index', :as => 'admin_root'
   
  # doctor root path
  get '/doctor_home/index' => 'doctor_home#index', :as => 'doctor_root'
  
  # nurse root path
  get '/nurse_home/index' => 'nurse_home#index', :as => 'nurse_root'
  
  
  
   
  
  # resources :provider_masters do 
    # resources :service_prov_extra_infos
  # end 
  
  
  namespace :api do
    namespace :v1 do
       resources :person_infos
    end
     
  end
  
 
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  
  get 'profile' => 'users#profile'
  get 'edit_profile' => 'person_infos#edit_profile'
  patch 'update_profile' => 'person_infos#update_profile'
  
  # credentials
  get 'user_credential' => 'users#user_credential'
  patch 'update_credential' => 'users#update_credential'
  
  
  
  
  # Enable and Disable country
  get       'enable_country'    =>  'country_masters#enable_country'
  get       'disable_country'   =>  'country_masters#disable_country'
  
  # Enable and disable region
  get       'enable_region'    =>  'region_masters#enable_region'
  get       'disable_region'   =>  'region_masters#disable_region'
  
  # Enable and disable city
  get       'enable_city'    =>  'city_town_masters#enable_city'
  get       'disable_city'   =>  'city_town_masters#disable_city'
  
  # Enable and disable suburb
  get       'enable_suburb'    =>  'suburb_masters#enable_suburb'
  get       'disable_suburb'   =>  'suburb_masters#disable_suburb'
  
  # Enable and disable provider type
  get       'enable_prov_type'    =>  'service_prov_types#enable_prov_type'
  get       'disable_prov_type'   =>  'service_prov_types#disable_prov_type'
  
  # Enable and disable service
  get       'enable_service'    =>  'service_masters#enable_service'
  get       'disable_service'   =>  'service_masters#disable_service'
  
  # Enable and disable service provider
  get       'enable_service_provider'    =>  'provider_masters#enable_service_provider'
  get       'disable_service_provider'   =>  'provider_masters#disable_service_provider'
  
  # Enable and disable provider service
  get       'enable_provider_service'    =>  'provider_services#enable_provider_service'
  get       'disable_provider_service'   =>  'provider_services#disable_provider_service'
  
  
  # Enable and disable user type
  get       'enable_user_type'    =>  'person_type_masters#enable_user_type'
  get       'disable_user_type'   =>  'person_type_masters#disable_user_type'
  
  
  # Enable and disable player
  get       'enable_player'    =>  'person_infos#enable_player'
  get       'disable_player'   =>  'person_infos#disable_player' 
  
    
  # Enable and disable human part
  get       'enable_part'    =>  'affected_system_masters#enable_part'
  get       'disable_part'   =>  'affected_system_masters#disable_part'  
  
     
  # Enable and disable allergy
  get       'enable_allergy'    =>  'allergies_masters#enable_allergy'
  get       'disable_allergy'   =>  'allergies_masters#disable_allergy' 
  
  # Enable and disable appointment type
  get       'enable_appointment_type'    =>  'appointment_types#enable_appointment_type'
  get       'disable_appointment_type'   =>   'appointment_types#disable_appointment_type'
  
  
  # Enable and disable pre_appointment
  get       'enable_pre_appointment'    =>  'pre_appointments#enable_pre_appointment'
  get       'disable_pre_appointment'   =>   'pre_appointments#disable_pre_appointment'
  
  # Enable and disable confirmed appointment
  get       'enable_appointment'    =>  'confirmed_appointments#enable_appointment'
  get       'disable_appointment'   =>   'confirmed_appointments#disable_appointment'
  
  # Enable and disable pre confirmed appointment
  get       'enable_pre_confirmed_appointment'    =>  'pre_confirmed_appointments#enable_pre_confirmed_appointment'
  get       'disable_pre_confirmed_appointment'   =>   'pre_confirmed_appointments#disable_pre_confirmed_appointment'
 
 # Enable and disable lab_service
  get       'enable_lab_service'    =>  'lab_services#enable_lab_service'
  get       'disable_lab_service'   =>  'lab_services#disable_lab_service'
  
  # Enable and disable pending registration
  get       'enable_pending_reg'    =>  'registrations#enable_pending_reg'
  get       'disable_pending_reg'   =>  'registrations#disable_pending_reg'

  # Enable and disable pending drug master
  get       'enable_drug'    =>  'drug_masters#enable_drug'
  get       'disable_drug'   =>  'drug_masters#disable_drug'

  # Enable and disable pending drug measuring unit
  get       'enable_unit'    =>  'measure_units#enable_unit'
  get       'disable_unit'   =>  'measure_units#disable_unit'

  # Enable and disable pending drug measuring unit
  get       'enable_price'    =>  'service_fee_masters#enable_price'
  get       'disable_price'   =>  'service_fee_masters#disable_price'





  # Approve registration
  get       'approve_registration'   =>  'registrations#approve_registration'
  get       'new_confirm_person_info'   =>  'person_info_extras#new_confirm_person_info' 
  post       'create_reg_confirm'   =>  'person_infos#create_reg_confirm'  
  post      'confirm_person_registration'   =>  'person_info_extras#confirm_person_registration'
  # post      'confirm_person_registration_prof_info'   =>  'person_infos#confirm_person_registration_prof'  
  

app/controllers/city_town_masters_controller.rb
class CityTownMastersController < ApplicationController
  before_action :set_city_town_master, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #load_and_authorize_resource
  # before_action :authenticate_user!
  #before_filter :load_permissions
  # GET /city_town_masters
  # GET /city_town_masters.json
  def index
    @city_town_masters = CityTownMaster.joins(:region_master).where(region_masters: {region_state_name: "Greater Accra"}).paginate(:page => params[:page], :per_page => 10).order('id desc')
    @region_masters = RegionMaster.all
    
    
    #search
   if params[:count]
      params[:count]
   else
     params[:count] = 10
   end
   
   if params[:page]
     page = params[:page].to_i
   else
     page = 1
   end
   
   if params[:per_page].present?
      # perpage = params[:per_page]
      @per_page = params[:per_page] || CityTownMaster.per_page || 10
      @city_town_masters = CityTownMaster.paginate( :per_page => @per_page, :page => params[:page])
   else
     perpage = 10
   end
   @per_page = params[:per_page] || CityTownMaster.per_page || 10
   page = if params[:page]
            params[:page].to_i
           else
            1
           end
           
           
          
# Filter by region/state name

if params[:region_state_name]
   @region_name = params[:region_state_name]
   logger.info "Then Region is #{@region_name.inspect}"
   @city_town_masters = CityTownMaster.joins(:region_master).where(region_masters: {region_state_name: @region_name}).paginate( :page => params[:page], :per_page => 10).order('id desc')
   
end
 
#            
   # per_page = 5
#    
   # offset = (page - 1) * per_page
   # limit = page * per_page
   # @array = *(offset...limit)


   # if  params[:search_value] && params[:search_value].strip != ''
#      
     # if params[:search_param] == 'firstname'
       # logger.info "the code comes to if  firstname............"
       # @contacts = Contact.firstname_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('ID asc')
#        
      # elsif params[:search_param] == 'lastname'
        # logger.info "the code comes to elsif lastname............."
        # @contacts = Contact.lastname_search(params[:search_value].strip).paginate(page: params[:page], per_page: params[:count]).order('ID asc')
#         
   # else
     # logger.info "the code comes to the else...."
      # @contacts = Contact.paginate(page: params[:page], per_page: params[:count]).order('ID desc')
      # @search_json = []
     # end
#     
    # elsif params[:search_param] == 'date'
       # logger.info "the code comes to elsif date............."
#        
       # start = (params["start_date"] + " " + "0:00:00")# Time.zone.parse(params["start_date"].to_s + " " + "0:00:00").utc # params["start_date"].to_s + "0:00:00"
       # ended = params["end_date"] + " " + ("23:59:59") # Time.zone.parse(params["end_date"].to_s + " " + "23:59:59").utc # params["end_date"].to_s + "23:59:59"
       # @contacts = Contact.search_date(start,ended).paginate(page: params[:page], per_page: params[:count]).order('ID asc')
#  
#      
   # end
   # p "JSON ARRAY: #{@search_json}"
#     
    
    respond_to do |format|
        format.js
        format.html
      # format.csv { send_data @contacts.to_csv}
      format.csv { send_data CityTownMaster.joins(:region_master).paginate(:page => params[:page], :per_page => 5).order('created_at desc').to_csv(options = {}, page, perpage)}
      format.xls { send_data CityTownMaster.all.paginate(:page => params[:page], :per_page => 10).order('created_at desc').to_csv(options={col_sep: "\t"}, page, perpage)}
    end
    
  end
  
  
  def all_city_excel
    @city_town_masters = CityTownMaster.all.order('created_at desc')
    respond_to do |format|
      # format.json {render json: @search_json[1..10]}
      # p "JSON ARRAY: #{@search_json}"
      format.html
      format.js
      format.csv { send_data @city_town_masters.to_csv }
      format.xls { send_data @city_town_masters.to_csv(options={col_sep: "\t"}) }
    end
  end

  # GET /city_town_masters/1
  # GET /city_town_masters/1.json
  def show
  end

  # GET /city_town_masters/new
  def new
    regions =RegionMaster.find(params[:region_id])
    @current_region_id = regions.id
    @region = regions.region_state_name
    @city_town_master = CityTownMaster.new
    # @region_masters = RegionMaster.all
  end

  # GET /city_town_masters/1/edit
  def edit
    @region_masters = RegionMaster.all
  end
  
  def enable_city
      city_id=params[:chosen]
      city = CityTownMaster.find(city_id)
     if city.update(:active_status => 1)
       redirect_to city_town_masters_path, notice: 'City was successfully enabled.'
     end
  end

  def disable_city 
      city_id=params[:chosen]
      
      city = CityTownMaster.find(city_id)
      # logger.info "country is: #{country.inspect}"
      
     if city.update(:active_status => 0)
       redirect_to city_town_masters_path, notice: 'City was successfully disabled.'
     end
     
  end
  
  def find_cities
    regions =RegionMaster.find(params[:region_id])
    @city_town_masters = CityTownMaster.where(region_id: regions.id).paginate(:page => params[:page], :per_page => 5).order('id desc')
     
    @region = regions.region_state_name
    
    @current_region_id = regions.id
    
    logger.info "Region is: #{@region.inspect}" 
  end
  
  

  # POST /city_town_masters
  # POST /city_town_masters.json
  def create
    @city_town_master = CityTownMaster.new(city_town_master_params)

    respond_to do |format|
      if @city_town_master.save
        @region_masters = RegionMaster.all.paginate(:page => params[:page], :per_page => 5).order('id desc')
        format.js { flash.now[:notice] = "City was successfully created." }
        format.html { redirect_to @city_town_master, notice: 'City town master was successfully created.' }
        format.json { render :show, status: :created, location: @city_town_master }
      else
        format.js { render :new }
        format.html { render :new }
        format.json { render json: @city_town_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /city_town_masters/1
  # PATCH/PUT /city_town_masters/1.json
  def update
    respond_to do |format|
      if @city_town_master.update(city_town_master_params)
        @city_town_masters = CityTownMaster.all.paginate(:page => params[:page], :per_page => 5).order('id desc')
        format.js { flash.now[:notice] = "City was successfully updated." }
        format.html { redirect_to @city_town_master, notice: 'City town master was successfully updated.' }
        format.json { render :show, status: :ok, location: @city_town_master }
      else
        @region_masters = RegionMaster.all
        format.js { render :edit }
        format.html { render :edit }
        format.json { render json: @city_town_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /city_town_masters/1
  # DELETE /city_town_masters/1.json
  def destroy
    @city_town_master.destroy
    respond_to do |format|
      format.html { redirect_to city_town_masters_url, notice: 'City town master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city_town_master
      @city_town_master = CityTownMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_town_master_params
      params.require(:city_town_master).permit(:city_town_name, :comment, :region_id, :entity_id, :user_id, :active_status, :change_status)
    end
end

app/helpers/city_town_masters_helper.rb
module CityTownMastersHelper
end

app/views/city_town_masters/_find_cities.html.erb
<% if flash[:notice] %>
  <p class="flash_notice " id = 'notes' style = "margin-top: 5px"><%= notice %></p>
<%end%>

<!-- <div class="col-md-2 col-xs-12"></div> -->
<div class="col-md-12 col-xs-12">
	<h4> <%= @region %>  </h4>
	<div class="table-responsive">
		<table class="table table-condensed table-bordered table-striped w3-card-4 ">
		  <thead>
		    <tr class="w3-teal">
		      <th>City/Towm</th>
		      <th>Status</th>
		      <th style="width: 15px">Details</th>
		    </tr>
		  </thead>
			
		  <tbody>
		    <% @city_town_masters.each do |city_town_master| %>
		      <tr>
		      	
		        <td><%= city_town_master.city_town_name %></td>
		  
		        <% if city_town_master.active_status == true %>  
		          <td style="color: ">Active</td>
		      		
		        <%elsif city_town_master.active_status == false %>
		          <td style="color: red">Inactive</td>
		      		
		        <%end%>
		        
		        <td style="15px"><%= link_to 'Details', city_town_master, remote: true, class: "w3-btn w3-indigo w3-hover-indigo w3-small w3-round-xlarge w3-middle " %></td>
		       </td>
		        
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		
		<%= will_paginate @city_town_masters,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "city_town_masters", :action => "find_cities", count: params[:count], page: params[:page] } %>
	</div>
	
	<div>
	 <%= link_to 'Back', region_masters_path, :remote=> true, class: "w3-button  w3-black w3-hover-black w3-right w3-small w3-round-xxlarge w3-card" %>
	 <%= link_to '+', new_city_town_master_path(:region_id => @current_region_id), :remote=> true, class: "w3-button w3-circle w3-teal w3-hover-teal w3-card" %>
	<br />
	</div>
<br>
</div>
 
<!-- <div class="col-md-2 col-xs-12"></div> -->

<script>
  $(function(){
    $('.pagination a').attr('data-remote', 'true')
  });

</script>


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 })
</script>

<!-- <%= link_to 'New City town master', new_city_town_master_path %> -->

app/views/city_town_masters/_form.html.erb
<%= simple_form_for(@city_town_master, :remote => true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :city_town_name, label: "City/Town" %>
    <%= f.input :region_id,as: :hidden, input_html: {value: @current_region_id} %>
     <%= f.input :comment, label: "Remark" %>
    <%= f.input :entity_id, as: :hidden %>
    <%= f.input :user_id, as: :hidden, input_html: {value: current_user.id} %>
    <%= f.input :active_status, as: :hidden, input_html: {value: 1} %>
    <%= f.input :change_status, as: :hidden, input_html: {value: 0} %>
  </div>

  <div class="form-actions">
    <%= link_to 'Back', region_masters_path, remote: true, class: "w3-left w3-button w3-small w3-round-large w3-blue w3-hover-blue" %>
    <%= f.button :submit, class: "w3-right w3-button w3-small w3-round-large w3-teal w3-hover-teal", value: "Add City" %>
    <br />
  </div>
<% end %>
<br />

app/views/city_town_masters/_index.html.erb
<% if flash[:notice] %>
  <p class="flash_notice " id = 'notes' style = "margin-top: 5px"><%= notice %></p>
<%end%>


<h4>Available Towns</h4>
<br />
<p style = 'text-align: center; font-family: tahoma; font-size: 15px;'>
   <b>Download:</b>  <%= link_to "CSV", city_town_masters_path(format: "csv" ), :class => "w3-hover-white" %> 
                     | <%= link_to "Excel", city_town_masters_path(format: "xls"), :class => "w3-hover-white" %> 
                     | <%= link_to "CSV-all", all_city_excel_path(format: "csv"), :class => "w3-hover-white", method: :get%> 
                     | <%= link_to "Excel-all", all_city_excel_path(format: "xls"),:class => "w3-hover-white", method: :get%>
</p>

<div class="pull-right" style = 'margin-top: -3%;'>
	 <label class="">Display <u>No</u>: </label> 
	  <%= select_tag :per_page, options_for_select([5,10, 20, 30, 40,50, 70,100], params[:per_page].to_i), :data => { :remote => true, 
	 	             :url => url_for( :controller => "city_town_masters", :action => "index" )
	 	             }, class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4", remote: true %>	                                                                                                        
</div>

<div class="pull-left" style = 'margin-top: -3%;'>
	 <label class="">Filter by Region/State: </label> 
	  <!-- <%= select("country_name", "country_name", CountryMaster.all.collect(&:country_name))  %> -->
	  <%= select_tag :region_state_name, options_from_collection_for_select(RegionMaster.all, "region_state_name", "region_state_name", @region_name), :data => {:remote => true, 
	  	:url => url_for(:controller => "city_town_masters", :action => "index")}, remote: true,  class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4", :prompt=> "Select to filter" %>
	 	      	                                                                                                        
 </div>

 <br />
<div class="table-responsive">
	<table class="table table-condensed table-bordered table-striped">
	  <thead>
	    <tr class="w3-teal">
	      <th>City town name</th>
	      <th>Region</th>
	      <th>Remark</th>
	      <!-- <th>Entity</th> -->
	      <th>Added by</th>
	      <th>Status</th>
	      <th>Suburbs</th>
	      <th colspan="2">Options</th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @city_town_masters.each do |city_town_master| %>
	      <tr>
	        <td><%= city_town_master.city_town_name %></td>
	        <td><%= city_town_master.region_master.region_state_name if city_town_master.region_master %></td>
	        <td><%= city_town_master.comment %></td>
	        <!-- <td><%= city_town_master.entity_id %></td> -->
	        <td><%= city_town_master.user.person_info.surname if city_town_master.user %> <%= city_town_master.user.person_info.other_names if city_town_master.user %></td>
	        
	        <% if city_town_master.active_status == true %>  
	          <td style="">Active</td>
	      		
	       <%elsif city_town_master.active_status == false %> 
	          <td style="color: red">Inactive</td>
	      		
	       <%end%>
	        
	        <!-- <td><%= city_town_master.active_status %></td> -->
	         <td style="width: 5px"><%= link_to "Suburbs", find_suburbs_path(:city_id => city_town_master.id), remote: true, class: "w3-button w3-indigo w3-hover-indigo w3-card w3-small w3-round w3-round-xxlarge" %></td> 
	        <!-- <td style="width: 5px"><%#= link_to 'view', city_town_master, remote: true, class: "w3-button w3-indigo w3-hover-indigo w3-card w3-small w3-round w3-round-xxlarge" %></td> -->
	        <td style="width: 5px"><%= link_to 'Edit', edit_city_town_master_path(city_town_master), remote: true, class: "w3-button w3-gray w3-card w3-hover-gray w3-small w3-round w3-round-xxlarge" %></td>
	        
	         <td style="width: 15px">
	       <% if city_town_master.active_status == false %>
	          <%= link_to 'Enable', enable_city_path(:chosen => city_town_master.id), data: { confirm: 'You are about to enable the selected city. Do you want to continue?' }, remote: true,  class: "w3-button w3-blue w3-hover-blue w3-small w3-round-xxlarge w3-card" %>
               
           <% else city_town_master.active_status == true %>
	           <%= link_to 'Disable', disable_city_path(:chosen => city_town_master.id), data: { confirm: 'You are about to disable the selected city. Do you want to continue?' }, remote: true,  class: "w3-button w3-red w3-hover-red w3-small w3-round w3-round-xxlarge w3-card" %> 
	          
           <% end %>
	        	
	        	
	       </td>
	        <!-- <td><%= link_to 'Destroy', city_town_master, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</div>
  
<div>
 <!-- <%#= link_to '+', new_city_town_master_path, :remote=> true, class: "w3-button w3-circle w3-teal w3-hover-teal w3-left w3-card-4" %> -->
 <%= will_paginate @city_town_masters,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "city_town_masters", :action => "index", count: params[:count], page: params[:page] } %>
</div>
<br>


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 })
</script>

<script>
  $(function(){
    $('.pagination a').attr('data-remote', 'true')
  });

</script>



<!-- <%= link_to 'New City town master', new_city_town_master_path %> -->

app/views/city_town_masters/add_cities.js.erb
$("#Region_State").html("<%= escape_javascript(render(:partial=>"form")) %>"); 

app/views/city_town_masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing City Town Masters</h1>

<table>
  <thead>
    <tr>
      <th>City town name</th>
      <th>Comment</th>
      <th>Region</th>
      <th>Entity</th>
      <th>User</th>
      <th>Active status</th>
      <th>Del status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @city_town_masters.each do |city_town_master| %>
      <tr>
        <td><%= city_town_master.city_town_name %></td>
        <td><%= city_town_master.comment %></td>
        <td><%= city_town_master.region_id %></td>
        <td><%= city_town_master.entity_id %></td>
        <td><%= city_town_master.user_id %></td>
        <td><%= city_town_master.active_status %></td>
        <td><%= city_town_master.del_status %></td>
        <td><%= link_to 'Show', city_town_master %></td>
        <td><%= link_to 'Edit', edit_city_town_master_path(city_town_master) %></td>
        <td><%= link_to 'Destroy', city_town_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City town master', new_city_town_master_path %>