config/routes.rb
Rails.application.routes.draw do

  
  
  resources :payment_states
  resources :feedbacks
  resources :subscription_remarks
  resources :subs_payments
  # resources :payment_states
  # resources :subs_payments
  # resources :subscription_remarks
  resources :subscription_new_mains
  # resources :feedbacks
  # root pages 
 
  resources :callback_statuses
  resources :payment_reqs
  resources :pre_payment_reqs
  resources :medication_details
  resources :service_fee_masters
  resources :billing_info_bill_items
  resources :patient_billing_infos
  resources :measure_units
  resources :drug_prices
  resources :drug_masters
  resources :decline_comments
  resources :pre_confirmed_appointments
  resources :referals
  resources :patient_med_records
  resources :pds_patient_prev_med_histories
  resources :confirmed_personal_doctor_services
  resources :engaged_user_services
  resources :user_services
  resources :roles
  resources :permission_roles
  resources :permissions
  resources :events
  resources :profesional_groups 
  resources :specialty_masters
  resources :confirmed_conditions
  resources :condition_masters
  resources :lab_detail_images
  resources :registrations
  resources :lab_details
  resources :lab_services
  resources :confirmed_appointments
  resources :requester_allergies
  resources :request_urgencies
  resources :request_categories
  devise_for :users
  resources :pre_appointments
  resources :appointment_types
  resources :allergies_masters
  resources :affected_system_masters
  resources :person_info_extras
  resources :person_contact_infos
  resources :provider_engaged_users
  resources :person_infos
  resources :person_type_masters
  resources :provider_masters
  resources :provider_services
  resources :service_prov_extra_infos
  resources :service_masters
  resources :service_prov_types
  resources :suburb_masters
  resources :city_town_masters
  resources :region_masters 
  resources :country_masters

   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # root pages 
  
  root 'home#welcome'

  get 'home/about' => 'home#welcome'
  
   get 'home/index', as: 'index' 
  #  get 'home/about', as: 'about'
  #  get 'home/services', as: 'services'
  #  get 'home/pricing', as: 'pricing'
  #  get 'home/blog', as: 'blog'
  #  get 'home/contact', as:  'contact'
   get 'home/elderlycare', as: 'elderlycare'
   get 'home/chronic_disease', as: 'chronic_disease'
   get 'home/annual_screening', as: 'annual_screening'
   get 'client_home/elderly', as: 'elderly'
   get 'client_home/elderlycare1', as: 'elderlycare1'
   get 'client_home/elderly_two', as: 'elderly_two'
   get 'client_home/elderly_three', as: 'elderly_three'
   get 'client_home/chronic_one', as: 'chronic_one'
   get 'client_home/chronic_two', as: 'chronic_two'
   get 'client_home/annual_screen_one', as: 'annual_screen_one'
   get 'client_home/annual_screen_two', as: 'annual_screen_two'
   get 'client_home/doctor_subscription', as: 'doctor_subscription'
   get 'client_home/doc_sub_detail', as: 'doc_sub_detail'
   get 'client_home/doc_remark_info', as: 'doc_remark_info'
   get 'client_home/subscriber_info', as: 'subscriber_info'
   get 'client_home/user_subs_detail', as: 'user_subs_detail'
   get 'client_home/user_pay', as: 'user_pay'
   get 'client_home/edit_info' => 'edit_info'



   post 'elderly_user_info' =>        'client_home#elderly_user_info'
   post 'elderly_user_info_two' =>        'client_home#elderly_user_info_two'
   post 'elderly_user_info_three' =>        'client_home#elderly_user_info_three'

   post 'chronic_user_info_one' =>        'client_home#chronic_user_info_one'
   post 'chronic_user_info_two' =>        'client_home#chronic_user_info_two'

   post 'annual_user_info_one' =>        'client_home#annual_user_info_one'
   post 'annual_user_info_two' =>        'client_home#annual_user_info_two' 
   

   post 'update_subscription' => 'subscription_new_mains#update_subscription'
   post 'remark_sub' => 'subscription_new_mains#remark_sub'
   post 'payme_user' => 'subscription_new_mains#payme_user'
   post 'ghinger_momo_callback' => 'home#ghinger_momo_callback'
   post 'ghinger_visa_callback' => 'home#ghinger_visa_callback'
  

  
  # Admin root path
   get '/admin/index' => 'admin#index', :as => 'admin_root'
   
  # doctor root path
  get '/doctor_home/index' => 'doctor_home#index', :as => 'doctor_root'
  
  # nurse root path
  get '/nurse_home/index' => 'nurse_home#index', :as => 'nurse_root'
  
  
  
   
  
  # resources :provider_masters do 
    # resources :service_prov_extra_infos
  # end 
  
  
  namespace :api do
    namespace :v1 do
       resources :person_infos
    end
     
  end
  
 
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  
  get 'profile' => 'users#profile'
  get 'edit_profile' => 'person_infos#edit_profile'
  patch 'update_profile' => 'person_infos#update_profile'
  
  # credentials
  get 'user_credential' => 'users#user_credential'
  patch 'update_credential' => 'users#update_credential'
  
  
  
  
  # Enable and Disable country
  get       'enable_country'    =>  'country_masters#enable_country'
  get       'disable_country'   =>  'country_masters#disable_country'
  
  # Enable and disable region
  get       'enable_region'    =>  'region_masters#enable_region'
  get       'disable_region'   =>  'region_masters#disable_region'
  
  # Enable and disable city
  get       'enable_city'    =>  'city_town_masters#enable_city'
  get       'disable_city'   =>  'city_town_masters#disable_city'
  
  # Enable and disable suburb
  get       'enable_suburb'    =>  'suburb_masters#enable_suburb'
  get       'disable_suburb'   =>  'suburb_masters#disable_suburb'
  
  # Enable and disable provider type
  get       'enable_prov_type'    =>  'service_prov_types#enable_prov_type'
  get       'disable_prov_type'   =>  'service_prov_types#disable_prov_type'
  
  # Enable and disable service
  get       'enable_service'    =>  'service_masters#enable_service'
  get       'disable_service'   =>  'service_masters#disable_service'
  
  # Enable and disable service provider
  get       'enable_service_provider'    =>  'provider_masters#enable_service_provider'
  get       'disable_service_provider'   =>  'provider_masters#disable_service_provider'
  
  # Enable and disable provider service
  get       'enable_provider_service'    =>  'provider_services#enable_provider_service'
  get       'disable_provider_service'   =>  'provider_services#disable_provider_service'
  
  
  # Enable and disable user type
  get       'enable_user_type'    =>  'person_type_masters#enable_user_type'
  get       'disable_user_type'   =>  'person_type_masters#disable_user_type'
  
  
  # Enable and disable player
  get       'enable_player'    =>  'person_infos#enable_player'
  get       'disable_player'   =>  'person_infos#disable_player' 
  
    
  # Enable and disable human part
  get       'enable_part'    =>  'affected_system_masters#enable_part'
  get       'disable_part'   =>  'affected_system_masters#disable_part'  
  
     
  # Enable and disable allergy
  get       'enable_allergy'    =>  'allergies_masters#enable_allergy'
  get       'disable_allergy'   =>  'allergies_masters#disable_allergy' 
  
  # Enable and disable appointment type
  get       'enable_appointment_type'    =>  'appointment_types#enable_appointment_type'
  get       'disable_appointment_type'   =>   'appointment_types#disable_appointment_type'
  
  
  # Enable and disable pre_appointment
  get       'enable_pre_appointment'    =>  'pre_appointments#enable_pre_appointment'
  get       'disable_pre_appointment'   =>   'pre_appointments#disable_pre_appointment'
  
  # Enable and disable confirmed appointment
  get       'enable_appointment'    =>  'confirmed_appointments#enable_appointment'
  get       'disable_appointment'   =>   'confirmed_appointments#disable_appointment'
  
  # Enable and disable pre confirmed appointment
  get       'enable_pre_confirmed_appointment'    =>  'pre_confirmed_appointments#enable_pre_confirmed_appointment'
  get       'disable_pre_confirmed_appointment'   =>   'pre_confirmed_appointments#disable_pre_confirmed_appointment'
 
 # Enable and disable lab_service
  get       'enable_lab_service'    =>  'lab_services#enable_lab_service'
  get       'disable_lab_service'   =>  'lab_services#disable_lab_service'
  
  # Enable and disable pending registration
  get       'enable_pending_reg'    =>  'registrations#enable_pending_reg'
  get       'disable_pending_reg'   =>  'registrations#disable_pending_reg'

  # Enable and disable pending drug master
  get       'enable_drug'    =>  'drug_masters#enable_drug'
  get       'disable_drug'   =>  'drug_masters#disable_drug'

  # Enable and disable pending drug measuring unit
  get       'enable_unit'    =>  'measure_units#enable_unit'
  get       'disable_unit'   =>  'measure_units#disable_unit'

  # Enable and disable pending drug measuring unit
  get       'enable_price'    =>  'service_fee_masters#enable_price'
  get       'disable_price'   =>  'service_fee_masters#disable_price'





  # Approve registration
  get       'approve_registration'   =>  'registrations#approve_registration'
  get       'new_confirm_person_info'   =>  'person_info_extras#new_confirm_person_info' 
  post       'create_reg_confirm'   =>  'person_infos#create_reg_confirm'  
  post      'confirm_person_registration'   =>  'person_info_extras#confirm_person_registration'
  # post      'confirm_person_registration_prof_info'   =>  'person_infos#confirm_person_registration_prof'  
  

app/helpers/confirmed_appointments_helper.rb
module ConfirmedAppointmentsHelper
end

app/views/confirmed_appointments/_index.html.erb
<% if flash[:notice] %>
  <p class="flash_notice " id = 'notes' style = "margin-top: 5px"><%= notice %></p>
<% end %>
<h4>Confirmed Appointments</h4>
<br />
<div class="pull-right" style = 'margin-top: -3%; display: inline-block'>
  <label class="">Display <u>No</u>: </label>
  <%= select_tag :per_page, options_for_select([5,10, 20, 30, 40,50, 70,100], params[:per_page].to_i), :data => { :remote => true,
	:url => url_for( :controller => "confirmed_appointments", :action => "index" )
	}, class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4", remote: true %>
</div>
<div class="pull-left" style = 'margin-top: -3%;'>
  <label class="w3-middle" >Fileter by: </label><br/>
  <ul class="list-inline">
    <li>
      <%= select_tag :provider_name, options_from_collection_for_select(ProviderMaster.all, "provider_name", "provider_name",  @provider_name), :data => {:remote => true,
		:url => url_for(:controller => "confirmed_appointments", :action => "index")}, remote: true,  class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4", :prompt => "Service Provider", style: "max-width: 100%; width: 100%; min-width: 100%"%>
    </li>
    <li>
      <%= select_tag :category, options_from_collection_for_select(RequestCategory.all, "category", "category",  @category), :data => {:remote => true,
	    :url => url_for(:controller => "confirmed_appointments", :action => "index")}, remote: true,  class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4", :prompt => "Request Category", style: "max-width: 100%; width: 100%; min-width: 100%" %>
    </li>
    <li>
      <%= select_tag :title, options_from_collection_for_select(AppointmentType.all, "title", "title",  @type), :data => {:remote => true,
	    :url => url_for(:controller => "confirmed_appointments", :action => "index")}, remote: true,  class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4", :prompt => "Appointment Type", style: "max-width: 100%; width: 100%; min-width: 100%" %>
    </li>
    <br>
    <br>
    <div class="w3-clear"></div>
    <li>
      <%= select_tag :user_type_title, options_from_collection_for_select(PersonTypeMaster.where('ref_id =?' , 'C'), "user_type_title", "user_type_title", @person_type), :data => {:remote => true,
      :url => url_for(:controller => "confirmed_appointments", :action => "index")}, remote: true,  class: "w3-bordered w3-round-xlarge w3-btn w3-small w3-card-4", :prompt => "Search Patient", style: "max-width: 100%; width: 100%; min-width: 100%" %>
    </li>
  </ul>
</div>
<br />
<br />
<div class="w3-clear"></div>
<p style = 'text-align: center; font-family: tahoma; font-size: 15px;'>
  <b>Download:</b>  <%= link_to "CSV", confirmed_appointments_path(format: "csv"), :class => "w3-hover-white"%>
  | <%= link_to "Excel", confirmed_appointments_path(format: "xls"), :class => "w3-hover-white" %>
  | <%= link_to "CSV-all", all_confirmed_appointment_excel_path(format: "csv"), :class => "w3-hover-white", method: :get%>
  | <%= link_to "Excel-all", all_confirmed_appointment_excel_path(format: "xls"),:class => "w3-hover-white", method: :get%>
</p>
<%= form_tag confirmed_appointments_path, :method => 'get', class: "form-inline w3-margin", html: { autocomplete: "off" }, remote: true, :id => "entity_search" do %>
  <% if @person_type == 'Patient' %>
    <%= text_field_tag :patient, params[:patient], class: "form-control w3-bordered ", :placeholder=> "Filter by Patient Name", autocomplete: "off", id: "patient"  %>
  <% elsif @person_type == 'Doctor' %>
    <%= text_field_tag :doctor, params[:doctor], class: "form-control w3-bordered ", :placeholder=> "Filter by Doctor Name", autocomplete: "off", id: "patient"  %>
  <% elsif @person_type == 'Nurse' %>
    <%= text_field_tag :nurse, params[:nurse], class: "form-control w3-bordered ", :placeholder=> "Filter by Nurse Name", autocomplete: "off", id: "patient"  %>
  <% elsif @person_type == 'Pharmacist' %>
    <%= text_field_tag :pharmacist, params[:pharmacist], class: "form-control w3-bordered ", :placeholder=> "Filter by Pharmacist Name", autocomplete: "off", id: "patient"  %>
  <% elsif @person_type == 'Laboratorist' %>
    <%= text_field_tag :laboratorist, params[:laboratorist], class: "form-control w3-bordered ", :placeholder=> "Filter by Laboratorist Name", autocomplete: "off", id: "patient"  %>
  <% end %>
  <% if @person_type.present? %>
    <%= submit_tag "Search", :name => nil,  class: "w3-btn w3-round w3-blue w3-tiny", id: "submitBtn" %>
    <br>
    <span>NB: <i style="color: red;"> Please type Surname first</i></span>
  <% end %>
<% end %>
<% if @person_type.nil? %>
  <%= link_to confirmed_appointments_path, remote: true do %>
    <span class="fa fa-refresh fa-2x"></span>
  <% end %>
<% end %>
<div class = "table-responsive">
  <table class="table table-condensed table-bordered table-striped w3-card-4">
    <thead>
      <tr class="w3-teal">
        <th>Requester</th>
        <th>Provider</th>
        <th>Appt Type</th>
        <th>Category</th>
        <th>Date/Time</th>
        <th>Billing</th>
        <th>Details</th>
        <th colspan="2">Options</th>
      </tr>
    </thead>
    <tbody>
      <% @confirmed_appointments.each do |confirmed_appointment| %>
        <tr>
          <td><%= truncate(confirmed_appointment.pre_appointment.person_info.surname, :length => 15) if confirmed_appointment.pre_appointment  %> <%= truncate(confirmed_appointment.pre_appointment.person_info.other_names, :length => 15) if confirmed_appointment.pre_appointment %></td>
          <% if confirmed_appointment.provider_master.present?%>
            <td><%= truncate(confirmed_appointment.provider_master.provider_name, :length => 10) if confirmed_appointment.provider_master %></td>
          <% else %>
            <td style="color: red;">Not applicable</td>
          <% end %>
          <td><%= truncate(confirmed_appointment.pre_appointment.appointment_type.title, :length => 10) if confirmed_appointment.pre_appointment %></td>
          <td><%= confirmed_appointment.pre_appointment.request_category.category  if confirmed_appointment.pre_appointment.request_category %></td>
          <td style="width: 15%;"><%= confirmed_appointment.confirmed_date.strftime("%F %R") if confirmed_appointment.confirmed_date  %></td>
          <td style="width: 10px;"><%= link_to 'Bill Info', bill_info_path(appointment_id: confirmed_appointment.id, from: "confirmed_appt"), remote: true, class: "w3-card-4 btn w3-khaki w3-hover-khaki w3-tiny w3-round-large" %></td>
          <td style="width: 5px"><%= link_to "Details", confirmed_appointment, remote: true, class: "w3-button w3-indigo w3-hover-indigo w3-card w3-small w3-round w3-round-xxlarge" %></td>
          <% if confirmed_appointment.pre_appointment %>
            <% if confirmed_appointment.pre_appointment.appointment_type_id == 'PD'%>
              <td style="width: 5px"><button class = "w3-button w3-white w3-card w3-hover-white w3-small w3-round w3-round-xxlarge">PDS</button></td>
            <% else %>
              <td style="width: 5px"><%= link_to 'Edit', edit_confirmed_appointment_path(confirmed_appointment), remote: true, class: "w3-button w3-gray w3-card w3-hover-gray w3-small w3-round w3-round-xxlarge",data: {"disable-with": "Please wait......"} %></td>
            <% end %>
          <%end%>
          <td style="width: 5px">
            <% if  confirmed_appointment.active_status == false %>
              <%= link_to 'Enable', enable_appointment_path(:chosen => confirmed_appointment.id), remote: true, data: { confirm: 'You are about to enable the selected appointment, do you want to continue?' },  class: "w3-button w3-blue w3-hover-blue w3-small w3-round-xxlarge w3-card",data: {"disable-with": "Please wait......"} %>
            <% elsif  confirmed_appointment.active_status == true %>
              <%= link_to 'Disable', disable_appointment_path(:chosen => confirmed_appointment.id), remote: true, data: { confirm: 'You are about to disable the selected appointment, do you want to continue?' },  class: "w3-button w3-red w3-hover-red w3-small w3-round w3-round-xxlarge w3-card" ,data: {"disable-with": "Please wait......"}%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div>
  <%= will_paginate @confirmed_appointments,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "confirmed_appointments", :action => "index", count: params[:count], page: params[:page] }  %>
  <br />
</div>
<br>
<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
      $('#notes').remove();
    }, 4000);
   });
</script>
<script>
  $(function(){
    $('.pagination a').attr('data-remote', 'true');
  });
</script>

app/views/confirmed_appointments/_new.html.erb
<br />
<div class="row">
	<div class="col-md-3 col-xs-12"></div>
	<div class="col-md-6 col-xs-12 w3-card-4 w3-round-large" >
		<h4>Confirm Appointment</h4>
		<%= render :partial=>  'form' %> 
	</div>
	<div class="col-md-3 col-xs-12"></div>
</div>
<br />

app/views/confirmed_appointments/edit.html.erb
<h1>Editing Confirmed Appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @confirmed_appointment %> |
<%= link_to 'Back', confirmed_appointments_path %>

app/views/confirmed_appointments/find_patient_details.html.erb
<div></div>
<div id="id01" class="w3-modal w3-card-4" style="display: block">
    <div class="w3-modal-content w3-animate-top w3-card-4 w3-white" style="width: 40%">
       <% if flash[:notice] %>
		   <p class="alert alert-info" id = 'notes' style = "margin-top: 5px"><%= notice %></p>
	   <% end %> 
      <header class="w3-container"> 
        <h4><%= @patient_detail.surname %> <%= @patient_detail.other_names %></h4> 
      </header>
      <br />
      <!-- <div class="col-md-1 col-xs-12"></div> -->
      <div class="col-md-12 col-xs-12 w3-padding">
      	<div class="w3-container "> 
      		<div class="row">
	      		<div class="col-md-6 col-sm-12">
	      			<table class="w3-table table-condensed table-striped">
	      				
				 	 <tr><td  style="width: 20%"><strong>DOB: </strong></td><td style="padding-left: 6%"><%= @patient_detail.dob %></td></tr>
				 	 <tr><td  style="width: 20%"><strong>Age: </strong></td><td style="padding-left: 6%"><%= ((Time.zone.now - @patient_detail.dob.to_time) / 1.year.seconds).floor if @patient_detail.dob %></td></tr>
				 	 <tr><td  style="width: 20%"><strong>Location: </strong></td><td style="padding-left: 6%"><%= @patient_detail.person_contact_infos[0].suburb_master.suburb_name if @patient_detail.person_contact_infos[0].suburb_id   %></td></tr>
				 	 
				    </table>	
	      		</div>
	      		<div class="col-md-6 col-sm-12">
      			  <table class="w3-table table-condensed table-striped">
		 	      <tr><td  style="width: 20%"><strong>Allergies: </strong></td><td style="padding-left: 6%">
		 	 	 <%= @patient_allergies.map {|patient_allergy| patient_allergy.allergies_master.title}.join(' , ') %> 	 	
		 	      </td></tr>
		 	      <tr><td  style="width: 20%"><strong>PMH: </strong></td><td style="padding-left: 6%"><%= raw @patient_pmh.prev_med_histry if @patient_pmh %></td></tr>
		 	     <tr><td  style="width: 20%"><strong>Current Meds: </strong></td><td style="padding-left: 6%"><%=  %></td></tr>	 	 
			    </table>
	      		</div>
      	   </div>
      	  <br />
      	  <h5><b style="color: blue"><u>List of Previous Encounters</u></b></h5>
      	  <div class="w3-clear"></div>
      	   <table class="table table-condensed table-striped w3-card">
      	    	<thead>
			    <tr class="">
			       <th>Details</th>
			       <th>Date</th> 
			       <th></th>
			    </tr>
			  </thead>		      
		      <tbody>
		      	<% @previous_encounters.each_with_index do |previous_encouter, index| %>
		      	<tr>
		      	 	<td> <%= index+1 %>. <%= previous_encouter.pre_appointment.appointment_type.title %> </td>
		      	 	<td><%= previous_encouter.created_at.strftime("%F %R") %> </td>
		      	 	<td><%= link_to "Details", record_detail_path(:confirmed_appt_id => previous_encouter.id), class: "w3-button w3-sand w3-hover-sand w3-card-4 w3-small w3-round-xlarge" %> </td>
		      	 </tr>     	     	    
      	        <% end %>
		      </tbody>
		       
			</table> 
			
       </div> 
      </div>        

		      <footer class="w3-container"> 
		      	<%= will_paginate @previous_encounters, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "confirmed_appointments", :action => "find_patient_details", count: params[:count], page: params[:page] }  %>  
		      <br /><br />
		      <div class="w3-clear"></div>
		       <%= link_to 'New Record', patient_confirmed_unattended_to_appt_path(:patient_id => @patient_id, :doctor_id => @doctor_id), class: "w3-button w3-yellow w3-card w3-left w3-hover-yellow" %>
		       <%= link_to 'Place an Order', place_order_path(:patient_id => @patient_id, :doctor_id => @doctor_id), class: "w3-button w3-yellow w3-card w3-right w3-hover-yellow" %>
		       <div class="clearfix w3-clear"></div>
		       <br /> 
		       <%= link_to 'Back', doctor_pds_path, class: "w3-button w3-black w3-hover-black  w3-card-4 w3-small w3-round-xlarge w3-right" %>
		      </footer>
     
      <br />
    </div>
    <br />
</div>


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 });
</script> 

<script>
  $(function(){
    // $('.pagination a').attr('data-remote', 'true');
  });

</script>

app/views/confirmed_appointments/index.html.erb
<div class="w3-bar w3-black">
	<button class="w3-bar-item w3-button tablink  hidden" onclick="openCity(event,'G_Appt');">App</button>
    <!-- <button class="w3-bar-item w3-button tablink w3-teal " onclick="openCity(event,'Pre_appointment');">Pre Appointments</button>
    <button class="w3-bar-item w3-button tablink " onclick="openCity(event,'Confirm');">Confirmed Appointments</button>  
    <button class="w3-bar-item w3-button tablink" onclick="openCity(event,'PDS');">Confirmed PDS</button> -->
 </div>


<div id="G_App" class="w3-container w3-display-container city w3-border" style="display:none; margin-bottom: 5%">
  <span onclick="this.parentElement.style.display='none'"
  class="w3-button w3-large w3-display-topright">&times;</span>
  <br /><br />
    <%= render :partial=> 'doctor_appointments' %>
</div>



<br /><br />
<div class="clearfix"></div>

<script>
function openCity(evt, cityName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" w3-teal", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " w3-teal";
}
</script>








<!-- <p id="notice"><%= notice %></p>

<h1>Listing Confirmed Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Pre appointment</th>
      <th>Provider</th>
      <th>Complaint desc</th>
      <th>Confirmed date</th>
      <th>Confirmed time</th>
      <th>Comment</th>
      <th>User</th>
      <th>Entity</th>
      <th>Active status</th>
      <th>Del status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @confirmed_appointments.each do |confirmed_appointment| %>
      <tr>
        <td><%= confirmed_appointment.pre_appointment_id %></td>
        <td><%= confirmed_appointment.provider_id %></td>
        <td><%= confirmed_appointment.complaint_desc %></td>
        <td><%= confirmed_appointment.confirmed_date %></td>
        <td><%= confirmed_appointment.confirmed_time %></td>
        <td><%= confirmed_appointment.comment %></td>
        <td><%= confirmed_appointment.user_id %></td>
        <td><%= confirmed_appointment.entity_id %></td>
        <td><%= confirmed_appointment.active_status %></td>
        <td><%= confirmed_appointment.del_status %></td>
        <td><%= link_to 'Show', confirmed_appointment %></td>
        <td><%= link_to 'Edit', edit_confirmed_appointment_path(confirmed_appointment) %></td>
        <td><%= link_to 'Destroy', confirmed_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Confirmed appointment', new_confirmed_appointment_path %> -->

app/views/confirmed_appointments/index.js.erb
$("#Confirm").html("<%= escape_javascript(render(:partial =>"index")) %>");


 

app/views/confirmed_appointments/new.html.erb
<h1>New Confirmed Appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', confirmed_appointments_path %>

app/views/confirmed_appointments/new.js.erb
$("#Pre_appointment").html("<%= escape_javascript(render(:partial =>"new")) %>");
<!-- $("#Pre_appointment").html("<%= escape_javascript(render(:partial =>"pre_appointment_detail")) %>"); -->

app/views/confirmed_appointments/update.js.erb
$("#Confirm").html("<%= escape_javascript(render(:partial =>"show")) %>");