config/routes.rb
Rails.application.routes.draw do

  
  
  resources :payment_states
  resources :feedbacks
  resources :subscription_remarks
  resources :subs_payments
  # resources :payment_states
  # resources :subs_payments
  # resources :subscription_remarks
  resources :subscription_new_mains
  # resources :feedbacks
  # root pages 
 
  resources :callback_statuses
  resources :payment_reqs
  resources :pre_payment_reqs
  resources :medication_details
  resources :service_fee_masters
  resources :billing_info_bill_items
  resources :patient_billing_infos
  resources :measure_units
  resources :drug_prices
  resources :drug_masters
  resources :decline_comments
  resources :pre_confirmed_appointments
  resources :referals
  resources :patient_med_records
  resources :pds_patient_prev_med_histories
  resources :confirmed_personal_doctor_services
  resources :engaged_user_services
  resources :user_services
  resources :roles
  resources :permission_roles
  resources :permissions
  resources :events
  resources :profesional_groups 
  resources :specialty_masters
  resources :confirmed_conditions
  resources :condition_masters
  resources :lab_detail_images
  resources :registrations
  resources :lab_details
  resources :lab_services
  resources :confirmed_appointments
  resources :requester_allergies
  resources :request_urgencies
  resources :request_categories
  devise_for :users
  resources :pre_appointments
  resources :appointment_types
  resources :allergies_masters
  resources :affected_system_masters
  resources :person_info_extras
  resources :person_contact_infos
  resources :provider_engaged_users
  resources :person_infos
  resources :person_type_masters
  resources :provider_masters
  resources :provider_services
  resources :service_prov_extra_infos
  resources :service_masters
  resources :service_prov_types
  resources :suburb_masters
  resources :city_town_masters
  resources :region_masters 
  resources :country_masters

   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  # root pages 
  
  root 'home#welcome'

  get 'home/about' => 'home#welcome'
  
   get 'home/index', as: 'index' 
  #  get 'home/about', as: 'about'
  #  get 'home/services', as: 'services'
  #  get 'home/pricing', as: 'pricing'
  #  get 'home/blog', as: 'blog'
  #  get 'home/contact', as:  'contact'
   get 'home/elderlycare', as: 'elderlycare'
   get 'home/chronic_disease', as: 'chronic_disease'
   get 'home/annual_screening', as: 'annual_screening'
   get 'client_home/elderly', as: 'elderly'
   get 'client_home/elderlycare1', as: 'elderlycare1'
   get 'client_home/elderly_two', as: 'elderly_two'
   get 'client_home/elderly_three', as: 'elderly_three'
   get 'client_home/chronic_one', as: 'chronic_one'
   get 'client_home/chronic_two', as: 'chronic_two'
   get 'client_home/annual_screen_one', as: 'annual_screen_one'
   get 'client_home/annual_screen_two', as: 'annual_screen_two'
   get 'client_home/doctor_subscription', as: 'doctor_subscription'
   get 'client_home/doc_sub_detail', as: 'doc_sub_detail'
   get 'client_home/doc_remark_info', as: 'doc_remark_info'
   get 'client_home/subscriber_info', as: 'subscriber_info'
   get 'client_home/user_subs_detail', as: 'user_subs_detail'
   get 'client_home/user_pay', as: 'user_pay'
   get 'client_home/edit_info' => 'edit_info'



   post 'elderly_user_info' =>        'client_home#elderly_user_info'
   post 'elderly_user_info_two' =>        'client_home#elderly_user_info_two'
   post 'elderly_user_info_three' =>        'client_home#elderly_user_info_three'

   post 'chronic_user_info_one' =>        'client_home#chronic_user_info_one'
   post 'chronic_user_info_two' =>        'client_home#chronic_user_info_two'

   post 'annual_user_info_one' =>        'client_home#annual_user_info_one'
   post 'annual_user_info_two' =>        'client_home#annual_user_info_two' 
   

   post 'update_subscription' => 'subscription_new_mains#update_subscription'
   post 'remark_sub' => 'subscription_new_mains#remark_sub'
   post 'payme_user' => 'subscription_new_mains#payme_user'
   post 'ghinger_momo_callback' => 'home#ghinger_momo_callback'
   post 'ghinger_visa_callback' => 'home#ghinger_visa_callback'
  

  
  # Admin root path
   get '/admin/index' => 'admin#index', :as => 'admin_root'
   
  # doctor root path
  get '/doctor_home/index' => 'doctor_home#index', :as => 'doctor_root'
  
  # nurse root path
  get '/nurse_home/index' => 'nurse_home#index', :as => 'nurse_root'
  
  
  
   
  
  # resources :provider_masters do 
    # resources :service_prov_extra_infos
  # end 
  
  
  namespace :api do
    namespace :v1 do
       resources :person_infos
    end
     
  end
  
 
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_in'
  end

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  post 'create_user' => 'users#create', as: :create_user
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'

  get '/users/:id' => 'users#show', :as => 'user'
  delete 'users/:id' => 'users#destroy'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  
  get 'profile' => 'users#profile'
  get 'edit_profile' => 'person_infos#edit_profile'
  patch 'update_profile' => 'person_infos#update_profile'
  
  # credentials
  get 'user_credential' => 'users#user_credential'
  patch 'update_credential' => 'users#update_credential'
  
  
  
  
  # Enable and Disable country
  get       'enable_country'    =>  'country_masters#enable_country'
  get       'disable_country'   =>  'country_masters#disable_country'
  
  # Enable and disable region
  get       'enable_region'    =>  'region_masters#enable_region'
  get       'disable_region'   =>  'region_masters#disable_region'
  
  # Enable and disable city
  get       'enable_city'    =>  'city_town_masters#enable_city'
  get       'disable_city'   =>  'city_town_masters#disable_city'
  
  # Enable and disable suburb
  get       'enable_suburb'    =>  'suburb_masters#enable_suburb'
  get       'disable_suburb'   =>  'suburb_masters#disable_suburb'
  
  # Enable and disable provider type
  get       'enable_prov_type'    =>  'service_prov_types#enable_prov_type'
  get       'disable_prov_type'   =>  'service_prov_types#disable_prov_type'
  
  # Enable and disable service
  get       'enable_service'    =>  'service_masters#enable_service'
  get       'disable_service'   =>  'service_masters#disable_service'
  
  # Enable and disable service provider
  get       'enable_service_provider'    =>  'provider_masters#enable_service_provider'
  get       'disable_service_provider'   =>  'provider_masters#disable_service_provider'
  
  # Enable and disable provider service
  get       'enable_provider_service'    =>  'provider_services#enable_provider_service'
  get       'disable_provider_service'   =>  'provider_services#disable_provider_service'
  
  
  # Enable and disable user type
  get       'enable_user_type'    =>  'person_type_masters#enable_user_type'
  get       'disable_user_type'   =>  'person_type_masters#disable_user_type'
  
  
  # Enable and disable player
  get       'enable_player'    =>  'person_infos#enable_player'
  get       'disable_player'   =>  'person_infos#disable_player' 
  
    
  # Enable and disable human part
  get       'enable_part'    =>  'affected_system_masters#enable_part'
  get       'disable_part'   =>  'affected_system_masters#disable_part'  
  
     
  # Enable and disable allergy
  get       'enable_allergy'    =>  'allergies_masters#enable_allergy'
  get       'disable_allergy'   =>  'allergies_masters#disable_allergy' 
  
  # Enable and disable appointment type
  get       'enable_appointment_type'    =>  'appointment_types#enable_appointment_type'
  get       'disable_appointment_type'   =>   'appointment_types#disable_appointment_type'
  
  
  # Enable and disable pre_appointment
  get       'enable_pre_appointment'    =>  'pre_appointments#enable_pre_appointment'
  get       'disable_pre_appointment'   =>   'pre_appointments#disable_pre_appointment'
  
  # Enable and disable confirmed appointment
  get       'enable_appointment'    =>  'confirmed_appointments#enable_appointment'
  get       'disable_appointment'   =>   'confirmed_appointments#disable_appointment'
  
  # Enable and disable pre confirmed appointment
  get       'enable_pre_confirmed_appointment'    =>  'pre_confirmed_appointments#enable_pre_confirmed_appointment'
  get       'disable_pre_confirmed_appointment'   =>   'pre_confirmed_appointments#disable_pre_confirmed_appointment'
 
 # Enable and disable lab_service
  get       'enable_lab_service'    =>  'lab_services#enable_lab_service'
  get       'disable_lab_service'   =>  'lab_services#disable_lab_service'
  
  # Enable and disable pending registration
  get       'enable_pending_reg'    =>  'registrations#enable_pending_reg'
  get       'disable_pending_reg'   =>  'registrations#disable_pending_reg'

  # Enable and disable pending drug master
  get       'enable_drug'    =>  'drug_masters#enable_drug'
  get       'disable_drug'   =>  'drug_masters#disable_drug'

  # Enable and disable pending drug measuring unit
  get       'enable_unit'    =>  'measure_units#enable_unit'
  get       'disable_unit'   =>  'measure_units#disable_unit'

  # Enable and disable pending drug measuring unit
  get       'enable_price'    =>  'service_fee_masters#enable_price'
  get       'disable_price'   =>  'service_fee_masters#disable_price'





  # Approve registration
  get       'approve_registration'   =>  'registrations#approve_registration'
  get       'new_confirm_person_info'   =>  'person_info_extras#new_confirm_person_info' 
  post       'create_reg_confirm'   =>  'person_infos#create_reg_confirm'  
  post      'confirm_person_registration'   =>  'person_info_extras#confirm_person_registration'
  # post      'confirm_person_registration_prof_info'   =>  'person_infos#confirm_person_registration_prof'  
  

app/models/requester_allergy.rb
class RequesterAllergy < ActiveRecord::Base
  # self.primary_key = "pre_appointment_id"
  self.primary_key = "requester_id"
  
  belongs_to :pre_appointment, class_name: "PreAppointment", foreign_key: :pre_appointment_id
  belongs_to :allergies_master, class_name: "AllergiesMaster", foreign_key: :allergy_id
  belongs_to :person_info, class_name: "PersonInfo", foreign_key: :requester_id
end
 

app/helpers/requester_allergies_helper.rb
module RequesterAllergiesHelper
end

app/views/requester_allergies/_add_allergy.html.erb
<h4>Select Allergie(s) for the selected Pre Appointment</h4>
<%= render 'allergy_form' %>
  

app/views/requester_allergies/_allergy_form.html.erb
<%= simple_form_for(@requester_allergy, remote: true) do |f| %>
  <%= f.error_notification %>
<div></div>
<div id="id01" class="w3-modal w3-card-4" style="display: block">
    <div class="w3-modal-content w3-animate-right w3-card-4 w3-light-gray" style="width: 40%; max-height: 80%; overflow-y: auto;">
      <div style="max-width: 70%; text-align: center; margin-left: 15%; margin-top: 15px">
	       <% if flash.now[:notice] %>
			  <p class="flash_notice "  style = ""><b><%= notice %></b></p>
		   <% end %>
    	</div>

      <header class="w3-container"> 
        <h4>Add allergy(s)</h4> 
        <p><b>Allergies by Patient: </b> <%= @pre_appt.allergies%></p>
      </header>
      <br />
      <!-- <div class="col-md-1 col-xs-12"></div> -->
      <div class="col-md-12 col-xs-12 w3-padding">
      	<div class="w3-container "> 	
      		<% count = 1 %>
      		
      		<% unless @allergies_masters.nil? %>
      		
      		   <%= f.input :pre_appointment_id, as: :hidden, input_html: {value: @pre_appointment_id} %>
      		   <%= f.input :requester_id, as: :hidden,  input_html: {value: @requester_id} %>
      		
	      		<% @allergies_masters.each do |allergy_master| %>
				 <table class="table table-condensed table-bordered table-striped">	
				 	<tr>
				 		<td style="width: 5%"><%= "#{count}. " %></td>
	         			<td style="width: 90%">&nbsp;<%= "#{allergy_master.title}" %></td>	
				 	    
				 	    <td >
				 	    	<% if @requester_allergies.include? allergy_master.id %>
				 	    		<input type="checkbox" name="allergy_id[<%=count%>[checkbox]]" checked="checked" />
				 	    	<% else %>
				 	    		<input type="checkbox" name="allergy_id[<%=count%>[checkbox]]"/>
				 	    	<%end%>	 	    	 
				 	    	    <input type="hidden" name="allergy_id[<%=count%>[id]]" value="<%= allergy_master.id %>">
				 	    	    <% count += 1 %>
				 	    </td>
				 	
				 	</tr>	
				 	
					  <!-- <div class="form-inputs">
					    <%= f.input :pre_appointment_id, input_html: {value: @pre_appointment_id} %>
					    <%= f.input :allergy_id %>
					    <%= f.input :comment %>
					    <%= f.input :user_id %>
					    <%= f.input :active_status %>
					    <%= f.input :del_status %>
					  </div> -->
					
					  <!-- <div class="form-actions">
					    <%= f.button :submit %>
					  </div> -->
					<% end %>
					
						</table>
			        </div>
			      </div> 
			      <footer class="w3-container">
			      	<!-- <%#= will_paginate @allergies_masters,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "requester_allergies", :action => "add_requester_allergy", count: params[:count], page: params[:page] }  %> -->
			     
					<div class="w3-clear"></div>
			      	<%= f.button :submit, class: "w3-left w3-button w3-small w3-round-large w3-teal w3-hover-teal w3-card-4 w3-round-xlarge w3-small", value: "Add" %>
			        <%= link_to 'Back', pre_appointments_path, :remote=> true, class: "w3-button w3-black w3-hover-black w3-right w3-card-4 w3-small w3-round-xlarge" %>
			       <br />
			      </footer>
			      <br />
	      <% end %>
      <%end%>
      
    </div>
    <br />
</div>


<script>
  $(function(){
    $('.pagination a').attr('data-remote', 'true')
  });

</script>


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 });
</script> 


app/views/requester_allergies/_edit_allergy.html.erb
<h4>Edit Allergies</h4>
<%= render "edit_allergy_form" %>

app/views/requester_allergies/_edit_allergy_form.html.erb
<%= simple_form_for(@requester_allergy, remote: true) do |f| %>
  <%= f.error_notification %>
<div></div>
<div id="id01" class="w3-modal w3-card-4" style="display: block">
    <div class="w3-modal-content w3-animate-right w3-card-4 w3-light-gray" style="width: 40%; max-height: 80%; overflow-y: auto;">
      <div style="max-width: 70%; text-align: center; margin-left: 15%; margin-top: 15px">
	       <% if flash.now[:notice] %>
			  <p class="flash_notice "  style = ""><b><%= notice %></b></p>
		   <% end %>
    	</div>

      <header class="w3-container"> 
        <h4>Add allergy(s) to the select Pre Appointment</h4> 
        <p><b style="color: red">NB: </b> Please select allergies that are new not checked<br /><br />
        	<b style="color: red">Allergies by Patient:</b>
        	<% if @patient_allergies.nil? %>
        	    No allergies
             <%else%>
        	    <%= @patient_allergies %>
        	<%end%>
        </p>
      </header>
      <br />
      <!-- <div class="col-md-1 col-xs-12"></div> -->
      <div class="col-md-12 col-xs-12 w3-padding">
      	<div class="w3-container "> 	
      		<% count = 1 %> 
      		
      		<% unless @allergies_masters.nil? %>
      		
      		  <%= f.input :pre_appointment_id, as: :hidden, input_html: {value: @pre_appointment_id} %>
      		  <%= f.input :requester_id, as: :hidden, input_html: {value: @requester_id} %>
      		
      		
	      		<% @allergies_masters.each do |allergy_master| %>
				 <table class="table table-condensed table-bordered table-striped">	
				 	<tr>
				 		<td style="width: 5%"><%= "#{count}. " %></td>
	         			<td style="width: 90%">&nbsp;<%= "#{allergy_master.title}" %></td>	
				 	    
				 	    <td >
				 	    	
					 	    <% if @allegy_list.include? allergy_master.id %>
					 	    	<input type="checkbox" name="allergy_id[<%=count%>[checkbox]]" checked="checked" />
					 	    <% else %>
					 	    	<input type="checkbox" name="allergy_id[<%=count%>[checkbox]]"/>
					 	    <%end%>	
					 	      	    	 
					 	    <input type="hidden" name="allergy_id[<%=count%>[id]]" value="<%= allergy_master.id %>">
					 	    <% count += 1 %>
				 	    </td>
				 	
				 	</tr>	
				 	
					<% end %>
				
						</table>
			        </div>
			      </div> 
			      <footer class="w3-container">
			      	<!-- <%#= will_paginate @allergies_masters,  renderer: BootstrapPagination::Rails, previous_label: 'Older', next_lable: 'Newer', class: "w3-right pagination-sm w3-card-4", :params => { :controller => "requester_allergies", :action => "add_requester_allergy", count: params[:count], page: params[:page] }  %> -->
			     
					<div class="w3-clear"></div>
			      	<%= f.button :submit, class: "w3-left w3-button w3-small w3-round-large w3-teal w3-hover-teal w3-card-4 w3-round-xlarge w3-small", value: "Update" %>
			        <%= link_to 'Back', pre_appointments_path, :remote=> true, class: "w3-button w3-black w3-hover-black w3-right w3-card-4 w3-small w3-round-xlarge" %>
			       <br />
			      </footer>
			      <br />
	      <% end %>
      <%end%>
      
    </div>
    <br />
</div>


<script>
  $(function(){
    $('.pagination a').attr('data-remote', 'true')
  });

</script>


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 });
</script> 


app/views/requester_allergies/_form.html.erb
<%= simple_form_for(@requester_allergy) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pre_appointment_id %>
    <%= f.input :allergy_id %>
    <%= f.input :comment %>
    <%= f.input :user_id %>
    <%= f.input :active_status %>
    <%= f.input :del_status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/requester_allergies/_show.html.erb
<div></div>
<div id="id01" class="w3-modal w3-card-4" style="display: block">
    <div class="w3-modal-content w3-animate-right w3-card-4 w3-light-gray" style="width: 40%">
      <div style="max-width: 70%; text-align: center; margin-left: 15%; margin-top: 15px">
	       <% if flash.now[:notice] %>
			  <p class="flash_notice "  style = ""><b><%= notice %></b></p>
		   <% end %>
    	</div>
      <br />
      <header class="w3-container"> 
        <h4>Allergies Details</h4> 
      </header>
      <!-- <div class="col-md-1 col-xs-12"></div> -->
      <div class="col-md-12 col-xs-12 w3-padding">
      	<div class="w3-container "> 	
		   <table class="table table-condensed table-bordered table-striped">
		   
		   	<% @requester_allergies.each_with_index do |requester_allergy, index| %>
		   	   <tr><td style="width: 2px"><%= index + 1 %></td><td style="padding-left: 6%""><%= requester_allergy.allergies_master.title %></td></tr>
		   	<%end%>	
				 					
		   </table>
	    </div>
	   </div> 
	  <footer class="w3-container">
		<%= link_to 'Back', pre_appointments_path, :remote=> true, class: "w3-button w3-black w3-hover-black w3-right w3-card-4 w3-small w3-round-xlarge" %>
	    <br /><br />
	  </footer>  
	  <div class="w3-clear"></div>    
    </div>
    <br />
</div>




<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('#notes').remove();
  }, 4000);
 });
</script> 

app/views/requester_allergies/add_requester_allergy.js.erb
$("#Pre_appointment").html("<%= escape_javascript(render(:partial =>"add_allergy")) %>");

app/views/requester_allergies/create.js.erb
$("#Pre_appointment").html("<%= escape_javascript(render(:partial =>"show")) %>");

app/views/requester_allergies/edit.html.erb
<h1>Editing Requester Allergy</h1>

<%= render 'form' %>

<%= link_to 'Show', @requester_allergy %> |
<%= link_to 'Back', requester_allergies_path %>

app/views/requester_allergies/edit_allergy.js.erb
$("#Pre_appointment").html("<%= escape_javascript(render(:partial =>"edit_allergy")) %>");

app/views/requester_allergies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requester Allergies</h1>

<table>
  <thead>
    <tr>
      <th>Pre appointment</th>
      <th>Allergy</th>
      <th>Comment</th>
      <th>User</th>
      <th>Active status</th>
      <th>Del status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requester_allergies.each do |requester_allergy| %>
      <tr>
        <td><%= requester_allergy.pre_appointment_id %></td>
        <td><%= requester_allergy.allergy_id %></td>
        <td><%= requester_allergy.comment %></td>
        <td><%= requester_allergy.user_id %></td>
        <td><%= requester_allergy.active_status %></td>
        <td><%= requester_allergy.del_status %></td>
        <td><%= link_to 'Show', requester_allergy %></td>
        <td><%= link_to 'Edit', edit_requester_allergy_path(requester_allergy) %></td>
        <td><%= link_to 'Destroy', requester_allergy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Requester allergy', new_requester_allergy_path %>

app/views/requester_allergies/new.html.erb
<h1>New Requester Allergy</h1>

<%= render 'form' %>

<%= link_to 'Back', requester_allergies_path %>

app/views/requester_allergies/show.js.erb
$("#Pre_appointment").html("<%= escape_javascript(render(:partial =>"show")) %>");

app/views/requester_allergies/update.js.erb
$("#Pre_appointment").html("<%= escape_javascript(render(:partial =>"show")) %>");